WEB/Workshop-PetStore/PetStore/Web/PetStore.Web/Models/ErrorViewModel.cs
using System;

namespace PetStore.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WEB/Workshop-PetStore/PetStore/Web/PetStore.Web/Models/Pets/AllPetsViewModel.cs
namespace PetStore.Web.Models.Pets
{
    using Services.Models.Pet;
    using System;
    using System.Collections.Generic;

    public class AllPetsViewModel
    {
        public IEnumerable<PetListingServiceModel> Pets { get; set; }

        public int Total { get; set; }

        public int CurrentPage { get; set; }

        public int PreviousPage => this.CurrentPage - 1;

        public int NextPage => this.CurrentPage + 1;

        public bool PreviousDisabled => this.CurrentPage == 1;

        public bool NextDisabled
        {
            get
            {
                var maxPage = Math.Ceiling(((double)this.Total) / 25);

                return maxPage == this.NextPage;
            }
        }
    }
}

WEB/Workshop-PetStore/PetStore/Web/PetStore.Web/Models/Pets/PetListingResponceModel.cs
namespace PetStore.Web.Models.Pets
{
    public class PetListingResponceModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Breed { get; set; }

        public decimal Price { get; set; }
    }
}

WEB/Workshop-PetStore/PetStore/Web/PetStore.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PetStore.Web.Models;

namespace PetStore.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WEB/Workshop-PetStore/PetStore/Web/PetStore.Web/Controllers/PetsController.cs
namespace PetStore.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Models.Pets;
    using Services;

    public class PetsController : Controller
    {
        private readonly IPetService pets;

        public PetsController(IPetService pets)
            => this.pets = pets;

        public IActionResult All(int page = 1) 
        {
            var allPets = this.pets.All(page);
            var totalPets = this.pets.Total();

            var model = new AllPetsViewModel
            {
                Pets = allPets,
                Total = totalPets,
                CurrentPage = page
            };

            return View(model);
        }

        public IActionResult Delete(int id)
        {
            var pet = this.pets.Details(id);

            if (pet == null)
            {
                return NotFound();
            }

            return View(pet);
        }

        public IActionResult ConfirmDelete(int id)
        {
            var deleted = this.pets.Delete(id);

            if (!deleted)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(All));
        }
    }
}

WEB/Workshop-PetStore/PetStore/Web/PetStore.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WEB/Workshop-PetStore/PetStore/Web/PetStore.Web/Views/Pets/All.cshtml
@model AllPetsViewModel

<h1>All Pets</h1>

<div>
    <a href="/Pets/All?page=@Model.PreviousPage" class="float-left btn btn-info @(Model.PreviousDisabled ? "disabled" : string.Empty)">Prev</a>
    <a href="/Pets/All?page=@Model.NextPage" class="float-right btn btn-info @(Model.NextDisabled ? "disabled" : string.Empty)">Next</a>
</div>

<table class="table table-bordered table-striped">
    <tr>
        <th>
            Type
        </th>
        <th>
            Breed
        </th>
        <th>
            Price
        </th>
        <th>
        </th>
    </tr>

    @foreach (var pet in Model.Pets)
    {
        <tr>
            <td>
                @pet.Category
            </td>
            <td>
                @pet.Breed
            </td>
            <td>
                $@pet.Price
            </td>
            <td>
                <a href="/Pets/Delete/@pet.Id" class="btn btn-danger btn-sm">Delete</a>
            </td>
        </tr>
    }
</table>

WEB/Workshop-PetStore/PetStore/Web/PetStore.Web/Views/Pets/Delete.cshtml
@model PetDetailsServiceModel

<h1>Are you sure you want to delete the following pet?</h1>

<div>
    <p>@Model.Category</p>
    <p>@Model.Breed</p>
    <p>@Model.DateOfBirth.ToShortDateString()</p>
    <p>@Model.Gender</p>
    <p>@Model.Description</p>
    <p>@Model.Price</p>
</div>

<div>
    <a href="/Pets/All" class="btn btn-info">No</a> &nbsp; <a href="/Pets/ConfirmDelete/@Model.Id" class="btn btn-info btn-danger">YES!</a>
</div>

WEB/Workshop-PetStore/PetStore/Web/PetStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetStore.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PetStore.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pets" asp-action="All">Pets</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PetStore.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>